### ISSUE TITLE
Voting power is 0 for all dreps

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#174]
Investigate the reason for voting power being 0 for all internal dreps.

### Acceptance Criteria
- [x] Fix or find alternate query to query actual voting power of dreps.

**Comment by Sital999** [comment]
Since no delegation was made on all the internal dreps as they were only registered, the voting power of all internal dreps was 0. Also for the voting power to be reflected it takes one epoch so as an alternative, we can fetch the total number of delegations made for the given `drep` and can show it as a live status on the frontend.
